services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/n8n-nodes-timizer/dist
      - ./package.json:/home/node/.n8n/custom/node_modules/n8n-nodes-timizer/package.json
      - ./certs:/certs:ro
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - N8N_PROTOCOL=https
      - N8N_SSL_KEY=/certs/localhost-key.pem
      - N8N_SSL_CERT=/certs/localhost.pem
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL:-https://localhost:5678/}

volumes:
  n8n_data:
